import { SRC, type BankQuestion } from "./types";

const c = "rhythms" as const;

export const rhythmsQuestions: BankQuestion[] = [
  // ─────────────── SEEKER ───────────────
  {
    id: "rhy-s-01", category: c, difficulty: "seeker", type: "mcq",
    prompt: "The tabla, a pair of hand drums, is most closely associated with which music tradition?",
    options: ["Hindustani classical music", "Carnatic classical music", "Sufi qawwali only", "Rabindra Sangeet only"],
    answer: 0,
    explanation: {
      title: "Tabla: the heartbeat of Hindustani music",
      body: "The tabla is the main percussion instrument of Hindustani (North Indian) classical music. It is a pair of drums: the smaller right-hand drum called the dayan and the larger left-hand bass drum called the bayan. Tabla players keep the tala cycle and also improvise alongside the main artist.",
      trivia: "The black circle on each drumhead, called the syahi, is a paste of iron filings, soot and flour that gives the tabla its ringing, bell-like tone.",
    },
    source: SRC.britannica("art/tabla", "Tabla"),
  },
  {
    id: "rhy-s-02", category: c, difficulty: "seeker", type: "mcq",
    prompt: "Which barrel-shaped drum is the principal percussion instrument of a Carnatic concert?",
    options: ["Dholak", "Mridangam", "Pakhawaj", "Nagara"],
    answer: 1,
    explanation: {
      title: "Mridangam: the lead drum of South India",
      body: "The mridangam is a double-headed barrel drum played with both hands and is the main rhythmic accompaniment in Carnatic (South Indian) classical music. In most concerts the mridangam player also gets a solo section called the tani avartanam.",
      trivia: "The pakhawaj of the North and the mridangam of the South are close cousins; both descend from ancient barrel drums described in early Indian texts.",
    },
    source: SRC.britannica("art/mridangam", "Mridangam"),
  },
  {
    id: "rhy-s-03", category: c, difficulty: "seeker", type: "mcq",
    prompt: "Bharatanatyam, one of India's classical dance forms, developed mainly in which present-day state?",
    options: ["Kerala", "Tamil Nadu", "Odisha", "Andhra Pradesh"],
    answer: 1,
    explanation: {
      title: "Bharatanatyam of Tamil Nadu",
      body: "Bharatanatyam grew out of the temple and court dance traditions of Tamil Nadu. It combines pure dance (nritta), expressive storytelling (abhinaya) and precise geometric poses. In the 20th century artists such as Rukmini Devi Arundale helped bring it to the concert stage.",
      trivia: "Many Bharatanatyam poses can be seen carved on the gopurams of the Nataraja temple at Chidambaram.",
    },
    source: SRC.britannica("art/Bharata-natyam", "Bharatanatyam"),
  },
  {
    id: "rhy-s-04", category: c, difficulty: "seeker", type: "mcq",
    prompt: "Kathakali, famous for its elaborate makeup and costumes, is a dance-drama from which state?",
    options: ["Karnataka", "Kerala", "Manipur", "Assam"],
    answer: 1,
    explanation: {
      title: "Kathakali: stories told through the face",
      body: "Kathakali is a classical dance-drama of Kerala that retells episodes from the Ramayana and Mahabharata. Dancers never speak; the story is carried by hand gestures (mudras), eye movements and singers who narrate from the side of the stage.",
      trivia: "Makeup colours signal character types. Green, called pacha, is used for noble heroes such as Krishna and Arjuna.",
    },
    source: SRC.britannica("art/kathakali", "Kathakali"),
  },
  {
    id: "rhy-s-05", category: c, difficulty: "seeker", type: "true_false",
    prompt: "True or false: The name Kathak comes from the word katha, which means story.",
    answer: true,
    explanation: {
      title: "Kathak and the storytellers",
      body: "Kathak traces its roots to the kathakars, travelling storytellers of North India who narrated epics through music, mime and dance. Over time the form absorbed influences from temple traditions and the Mughal and Rajput courts, and it is now known for fast footwork and spins.",
      trivia: "A Kathak dancer can wear more than a hundred small bells (ghungroo) on each ankle and control them so precisely that a single bell rings.",
    },
    source: SRC.britannica("art/kathak", "Kathak"),
  },
  {
    id: "rhy-s-06", category: c, difficulty: "seeker", type: "mcq",
    prompt: "Teentaal, the most widely used rhythmic cycle in Hindustani music, has how many beats?",
    options: ["10", "12", "14", "16"],
    answer: 3,
    explanation: {
      title: "Teentaal: sixteen beats in four parts",
      body: "Teentaal has 16 beats (matras) grouped into four sections of four. Three sections are marked with a clap and one with a wave of the hand, which is where the name, meaning 'three claps', comes from.",
      trivia: "The first beat of any tala cycle is called sam. Musicians often build their improvisations so they land exactly on sam together.",
    },
    source: SRC.britannica("art/tala", "Tala"),
  },
  {
    id: "rhy-s-07", category: c, difficulty: "seeker", type: "odd_one_out",
    prompt: "Which one of these is NOT a percussion instrument?",
    options: ["Tabla", "Ghatam", "Sarangi", "Mridangam"],
    answer: 2,
    explanation: {
      title: "The sarangi is bowed, not struck",
      body: "The sarangi is a bowed string instrument carved from a single block of wood. It is prized for sounding close to the human voice, which is why it has long accompanied Hindustani vocalists. The tabla, ghatam and mridangam are all percussion instruments.",
      trivia: "Besides its three main playing strings, a sarangi can carry more than 30 sympathetic strings that resonate on their own.",
    },
    source: SRC.britannica("art/sarangi", "Sarangi"),
  },
  {
    id: "rhy-s-08", category: c, difficulty: "seeker", type: "mcq",
    prompt: "Ustad Bismillah Khan, awarded the Bharat Ratna in 2001, was a master of which instrument?",
    options: ["Sitar", "Shehnai", "Flute", "Sarod"],
    answer: 1,
    explanation: {
      title: "Bismillah Khan and the shehnai",
      body: "Ustad Bismillah Khan of Varanasi took the shehnai, a double-reed wind instrument once heard mainly at weddings and temples, to the classical concert stage. He played at the Red Fort on the eve of India's independence in 1947.",
      trivia: "He is one of only a handful of classical musicians to have received the Bharat Ratna, India's highest civilian honour.",
    },
    source: SRC.britannica("biography/Bismillah-Khan", "Bismillah Khan"),
  },
  {
    id: "rhy-s-09", category: c, difficulty: "seeker", type: "match",
    prompt: "Match each classical dance form with the state it comes from.",
    pairs: [
      ["Kuchipudi", "Andhra Pradesh"],
      ["Odissi", "Odisha"],
      ["Mohiniyattam", "Kerala"],
      ["Sattriya", "Assam"],
    ],
    explanation: {
      title: "A map of classical dance",
      body: "Kuchipudi takes its name from a village in Andhra Pradesh. Odissi comes from the temple traditions of Odisha. Mohiniyattam, the graceful 'dance of the enchantress', belongs to Kerala, and Sattriya grew in the Vaishnava monasteries (sattras) of Assam.",
    },
    source: SRC.sna,
  },
  {
    id: "rhy-s-10", category: c, difficulty: "seeker", type: "mcq",
    prompt: "Pandit Ravi Shankar, who introduced Indian classical music to audiences worldwide, played which instrument?",
    options: ["Sitar", "Santoor", "Veena", "Sarangi"],
    answer: 0,
    explanation: {
      title: "Ravi Shankar and the sitar",
      body: "Pandit Ravi Shankar was a sitar player of the Maihar gharana and a student of Ustad Allauddin Khan. From the 1950s onward his international tours and collaborations made the sitar one of the most recognised Indian instruments in the world.",
      trivia: "He received the Bharat Ratna in 1999.",
    },
    source: SRC.britannica("biography/Ravi-Shankar", "Ravi Shankar"),
  },
  {
    id: "rhy-s-11", category: c, difficulty: "seeker", type: "true_false",
    prompt: "True or false: Carnatic music is the classical tradition mainly associated with North India.",
    answer: false,
    explanation: {
      title: "Two great classical traditions",
      body: "Carnatic music is the classical tradition of South India, while Hindustani music is associated with the North. Both share core ideas such as raga (melodic framework) and tala (rhythmic cycle) but differ in style, repertoire and instruments.",
      trivia: "Carnatic concerts are built largely around composed songs called kritis, while Hindustani performances give more room to extended improvisation.",
    },
    source: SRC.britannica("art/Karnatak-music", "Carnatic music"),
  },
  {
    id: "rhy-s-12", category: c, difficulty: "seeker", type: "mcq",
    prompt: "How many dance forms does the Sangeet Natak Akademi recognise as classical?",
    options: ["Six", "Seven", "Eight", "Ten"],
    answer: 2,
    explanation: {
      title: "The eight classical dances",
      body: "The Sangeet Natak Akademi, India's national academy for music, dance and drama, recognises eight classical dance forms: Bharatanatyam, Kathak, Kathakali, Kuchipudi, Manipuri, Mohiniyattam, Odissi and Sattriya.",
      trivia: "Sattriya was the most recent addition to the list, recognised in the year 2000.",
    },
    source: SRC.sna,
  },
  {
    id: "rhy-s-13", category: c, difficulty: "seeker", type: "mcq",
    prompt: "The ghatam, used in Carnatic concerts, is essentially what kind of object?",
    options: ["A clay pot", "A metal plate", "A bamboo tube", "A conch shell"],
    answer: 0,
    explanation: {
      title: "Ghatam: music from a clay pot",
      body: "The ghatam is a narrow-mouthed clay pot played with the fingers, palms and even the belly of the pot against the player's stomach. It usually supports the mridangam in Carnatic concerts.",
      trivia: "Ghatam makers mix brass or iron filings into the clay to get the right pitch and a sharp, metallic ring.",
    },
    source: SRC.britannica("art/ghatam", "Ghatam"),
  },
  {
    id: "rhy-s-14", category: c, difficulty: "seeker", type: "mcq",
    prompt: "How many basic notes (swaras) make up the Indian musical scale, Sa Re Ga Ma Pa Dha Ni?",
    options: ["Five", "Six", "Seven", "Eight"],
    answer: 2,
    explanation: {
      title: "The seven swaras",
      body: "Indian music is built on seven basic notes: Sa, Re, Ga, Ma, Pa, Dha and Ni, together called the saptak. Sa and Pa are fixed, while the other five can take altered forms, giving musicians twelve pitches to work with.",
    },
    source: SRC.britannica("art/raga", "Raga"),
  },
  {
    id: "rhy-s-15", category: c, difficulty: "seeker", type: "mcq",
    prompt: "The energetic Bihu dance is performed during festivals in which state?",
    options: ["Assam", "Punjab", "Gujarat", "Sikkim"],
    answer: 0,
    explanation: {
      title: "Bihu of Assam",
      body: "Bihu dance is performed by young men and women during Rongali Bihu, the spring festival that marks the Assamese New Year in April. It is danced to the dhol, pepa (buffalo horn pipe) and taal cymbals.",
    },
    source: SRC.knowIndia,
  },
  {
    id: "rhy-s-16", category: c, difficulty: "seeker", type: "true_false",
    prompt: "True or false: Yakshagana is a traditional theatre form from Karnataka.",
    answer: true,
    explanation: {
      title: "Yakshagana of coastal Karnataka",
      body: "Yakshagana combines dance, music, dialogue and grand costumes to perform stories from the epics and Puranas. It is especially popular in coastal Karnataka, where performances traditionally ran through the night.",
    },
    source: SRC.sna,
  },
  {
    id: "rhy-s-17", category: c, difficulty: "seeker", type: "mcq",
    prompt: "Lavani, a folk form known for its powerful rhythm set to the dholki drum, belongs to which state?",
    options: ["Maharashtra", "Rajasthan", "West Bengal", "Tamil Nadu"],
    answer: 0,
    explanation: {
      title: "Lavani of Maharashtra",
      body: "Lavani is a song and dance form of Maharashtra known for its fast tempo and the beat of the dholki. It has been performed for centuries and was especially popular during the Peshwa period.",
    },
    source: SRC.sna,
  },
  {
    id: "rhy-s-18", category: c, difficulty: "seeker", type: "mcq",
    prompt: "Which Carnatic vocalist became the first musician to receive the Bharat Ratna, in 1998?",
    options: ["M. S. Subbulakshmi", "Lata Mangeshkar", "Kishori Amonkar", "D. K. Pattammal"],
    answer: 0,
    explanation: {
      title: "M. S. Subbulakshmi",
      body: "M. S. Subbulakshmi of Madurai was the first musician to be awarded the Bharat Ratna, in 1998. Her devotional recordings, such as the Venkatesa Suprabhatam, are still played in homes and temples every morning.",
      trivia: "In 1966 she performed at the United Nations General Assembly in New York.",
    },
    source: SRC.britannica("biography/M-S-Subbulakshmi", "M. S. Subbulakshmi"),
  },
  {
    id: "rhy-s-19", category: c, difficulty: "seeker", type: "odd_one_out",
    prompt: "Three of these are string instruments. Which one is a wind instrument?",
    options: ["Sitar", "Sarod", "Veena", "Bansuri"],
    answer: 3,
    explanation: {
      title: "The bansuri is a bamboo flute",
      body: "The bansuri is a side-blown bamboo flute, strongly linked in Indian art with Lord Krishna. The sitar, sarod and veena are all plucked string instruments.",
      trivia: "Pandit Hariprasad Chaurasia brought the bansuri to the centre of Hindustani classical concerts.",
    },
    source: SRC.britannica("art/bansuri", "Bansuri"),
  },
  {
    id: "rhy-s-20", category: c, difficulty: "seeker", type: "mcq",
    prompt: "Manipuri dance, known for its soft, flowing movements, is closely connected with which theme?",
    options: ["The Ras Lila of Radha and Krishna", "Battle scenes from the Mahabharata", "Harvest rituals of the Deccan", "Court life of the Mughals"],
    answer: 0,
    explanation: {
      title: "Manipuri and the Ras Lila",
      body: "Manipuri dance of Manipur is deeply tied to Vaishnava devotion, and its best-known pieces are the Ras Lilas, which depict Krishna's dance with Radha and the gopis. Dancers move with rounded, gentle steps, and the women wear a stiff, barrel-shaped skirt called the potloi.",
    },
    source: SRC.britannica("art/Manipuri", "Manipuri dance"),
  },
  {
    id: "rhy-s-21", category: c, difficulty: "seeker", type: "mcq",
    prompt: "Tansen, one of the most celebrated musicians in Indian history, was a court musician of which emperor?",
    options: ["Babur", "Akbar", "Aurangzeb", "Bahadur Shah Zafar"],
    answer: 1,
    explanation: {
      title: "Tansen at Akbar's court",
      body: "Tansen served at the court of the Mughal emperor Akbar in the 16th century and is counted among the 'nine jewels' (navaratnas) of that court. He was a master of dhrupad, and several ragas carry his name, such as Miyan ki Todi and Miyan ki Malhar.",
      trivia: "The Tansen Samaroh, a classical music festival, is held every year near his tomb in Gwalior.",
    },
    source: SRC.britannica("biography/Tansen", "Tansen"),
  },

  // ─────────────── HISTORIAN ───────────────
  {
    id: "rhy-h-01", category: c, difficulty: "historian", type: "mcq",
    prompt: "The Carnatic melakarta system organises ragas into how many parent scales?",
    options: ["32", "54", "72", "108"],
    answer: 2,
    explanation: {
      title: "72 melakartas",
      body: "The melakarta system classifies Carnatic ragas under 72 parent scales, each using all seven notes in both ascent and descent. The scheme was laid out by Venkatamakhin in his 17th-century treatise Chaturdandi Prakashika and later refined into its present form.",
      trivia: "The 72 scales come from a neat mathematical arrangement: 36 scales use the lower form of Ma, and 36 use the higher form.",
    },
    source: SRC.britannica("art/Karnatak-music", "Carnatic music"),
  },
  {
    id: "rhy-h-02", category: c, difficulty: "historian", type: "mcq",
    prompt: "Vishnu Narayan Bhatkhande grouped Hindustani ragas into how many parent scales, called thaats?",
    options: ["7", "10", "12", "72"],
    answer: 1,
    explanation: {
      title: "Bhatkhande's ten thaats",
      body: "In the early 20th century, musicologist Vishnu Narayan Bhatkhande organised Hindustani ragas under ten thaats, including Bilawal, Kalyan, Khamaj, Bhairav and Kafi. The system is still the standard way ragas are taught in North India, even though some ragas do not fit it neatly.",
    },
    source: SRC.britannica("art/raga", "Raga"),
  },
  {
    id: "rhy-h-03", category: c, difficulty: "historian", type: "mcq",
    prompt: "Which of these ragas is traditionally performed at dawn?",
    options: ["Yaman", "Bhairav", "Darbari Kanada", "Malkauns"],
    answer: 1,
    explanation: {
      title: "Raga Bhairav at daybreak",
      body: "Hindustani tradition links ragas to times of day. Bhairav, with its flattened Re and Dha, is a morning raga with a serious, devotional mood. Yaman is sung in the early evening, while Darbari Kanada and Malkauns belong to late night.",
      trivia: "Bhairav is also the name of one of Bhatkhande's ten thaats.",
    },
    source: SRC.britannica("art/raga", "Raga"),
  },
  {
    id: "rhy-h-04", category: c, difficulty: "historian", type: "mcq",
    prompt: "The rudra veena has traditionally been the instrument of which austere vocal genre?",
    options: ["Thumri", "Dhrupad", "Ghazal", "Tappa"],
    answer: 1,
    explanation: {
      title: "Rudra veena and dhrupad",
      body: "Dhrupad is the oldest surviving genre of Hindustani classical music, slow and meditative in character. The rudra veena, with two large gourd resonators, and the pakhawaj drum are its traditional companions.",
      trivia: "The Dagar family has kept the dhrupad tradition alive for around twenty generations.",
    },
    source: SRC.britannica("art/dhrupad", "Dhrupad"),
  },
  {
    id: "rhy-h-05", category: c, difficulty: "historian", type: "odd_one_out",
    prompt: "Which of these composers is NOT part of the Trinity of Carnatic music?",
    options: ["Tyagaraja", "Muthuswami Dikshitar", "Syama Sastri", "Purandara Dasa"],
    answer: 3,
    explanation: {
      title: "The Trinity and the grandfather",
      body: "The Trinity of Carnatic music are Tyagaraja, Muthuswami Dikshitar and Syama Sastri, who were all born in Tiruvarur in the 18th century. Purandara Dasa lived about two hundred years earlier and is honoured as the Pitamaha, or grandfather, of Carnatic music for creating its basic teaching lessons.",
    },
    source: SRC.britannica("art/Karnatak-music", "Carnatic music"),
  },
  {
    id: "rhy-h-06", category: c, difficulty: "historian", type: "mcq",
    prompt: "The Natya Shastra, the foundational text on Indian drama, dance and music, is attributed to whom?",
    options: ["Bharata Muni", "Kalidasa", "Sharngadeva", "Matanga"],
    answer: 0,
    explanation: {
      title: "Bharata's Natya Shastra",
      body: "The Natya Shastra is attributed to the sage Bharata and was compiled roughly between 200 BCE and 200 CE. It covers stagecraft, acting, dance, music and the theory of rasa, the emotional flavour an audience experiences.",
      trivia: "It describes eight rasas, including love, humour, compassion and heroism. Later scholars added a ninth, shanta (peace).",
    },
    source: SRC.britannica("topic/Natyashastra", "Natya Shastra"),
  },
  {
    id: "rhy-h-07", category: c, difficulty: "historian", type: "mcq",
    prompt: "Sangita Ratnakara, a 13th-century treatise respected by both Hindustani and Carnatic musicians, was written by whom?",
    options: ["Sharngadeva", "Venkatamakhin", "Amir Khusrau", "Jayadeva"],
    answer: 0,
    explanation: {
      title: "Sharngadeva's Sangita Ratnakara",
      body: "Sharngadeva wrote the Sangita Ratnakara at the Yadava court of Devagiri in the 13th century. Because it was written before the two traditions clearly separated, both Hindustani and Carnatic musicians treat it as a key reference.",
    },
    source: SRC.britannica("art/South-Asian-arts", "South Asian arts"),
  },
  {
    id: "rhy-h-08", category: c, difficulty: "historian", type: "chronology",
    prompt: "Arrange these musicians in the order they received the Bharat Ratna, earliest first.",
    items: ["M. S. Subbulakshmi", "Ravi Shankar", "Bismillah Khan", "Bhupen Hazarika"],
    explanation: {
      title: "Music and the Bharat Ratna",
      body: "M. S. Subbulakshmi was honoured in 1998, Ravi Shankar in 1999 and Bismillah Khan in 2001. Assamese singer and composer Bhupen Hazarika received it posthumously in 2019.",
    },
    source: { label: "Ministry of Home Affairs: List of Bharat Ratna recipients", url: "https://www.mha.gov.in/sites/default/files/ListofBRrecepients_09082019.pdf" },
  },
  {
    id: "rhy-h-09", category: c, difficulty: "historian", type: "match",
    prompt: "Match each instrument with its type.",
    pairs: [
      ["Sarangi", "Bowed string"],
      ["Santoor", "Hammered dulcimer"],
      ["Pakhawaj", "Barrel drum"],
      ["Bansuri", "Bamboo flute"],
    ],
    explanation: {
      title: "Four families of sound",
      body: "The sarangi is bowed. The santoor, from Kashmir, has around a hundred strings struck with light wooden mallets. The pakhawaj is a two-headed barrel drum used in dhrupad, and the bansuri is a side-blown bamboo flute.",
      trivia: "Pandit Shivkumar Sharma is credited with turning the santoor from a folk instrument into a classical one.",
    },
    source: SRC.britannica("art/South-Asian-arts", "South Asian arts"),
  },
  {
    id: "rhy-h-10", category: c, difficulty: "historian", type: "mcq",
    prompt: "In Hindustani rhythm, what does the term 'khali' refer to?",
    options: ["The first beat of the cycle", "An unaccented section marked by a wave of the hand", "The fastest tempo", "A drum solo"],
    answer: 1,
    explanation: {
      title: "Tali and khali",
      body: "A tala is divided into sections called vibhags. Stressed sections are shown with a clap (tali), and the unstressed section is shown with a wave of the hand (khali, meaning 'empty'). Tabla players often drop the bass drum during khali, which helps listeners keep track of the cycle.",
    },
    source: SRC.britannica("art/tala", "Tala"),
  },
  {
    id: "rhy-h-11", category: c, difficulty: "historian", type: "mcq",
    prompt: "Which Hindustani tala has 10 beats, divided 2 + 3 + 2 + 3?",
    options: ["Ektaal", "Rupak", "Jhaptaal", "Dadra"],
    answer: 2,
    explanation: {
      title: "Jhaptaal",
      body: "Jhaptaal is a 10-beat cycle split into sections of 2, 3, 2 and 3 beats. By comparison, Ektaal has 12 beats, Rupak has 7 and Dadra has 6.",
    },
    source: SRC.britannica("art/tala", "Tala"),
  },
  {
    id: "rhy-h-12", category: c, difficulty: "historian", type: "true_false",
    prompt: "True or false: Rupak taal is unusual because its cycle begins on a khali (wave) rather than a clap.",
    answer: true,
    explanation: {
      title: "Rupak starts empty",
      body: "Rupak is a 7-beat tala divided 3 + 2 + 2. Unlike most talas, its first beat, the sam, falls on a khali section and is shown with a wave instead of a clap. This gives Rupak its light, lilting feel.",
    },
    source: SRC.britannica("art/tala", "Tala"),
  },
  {
    id: "rhy-h-13", category: c, difficulty: "historian", type: "mcq",
    prompt: "Of the three main styles of Chhau dance, which one is performed without masks?",
    options: ["Seraikella Chhau", "Purulia Chhau", "Mayurbhanj Chhau", "All three use masks"],
    answer: 2,
    explanation: {
      title: "The three Chhau styles",
      body: "Chhau has three main styles named after where they are practised: Seraikella in Jharkhand, Purulia in West Bengal and Mayurbhanj in Odisha. Seraikella and Purulia dancers wear masks, while Mayurbhanj dancers perform barefaced. Chhau was inscribed on UNESCO's intangible heritage list in 2010.",
    },
    source: SRC.unescoIchIndia,
  },
  {
    id: "rhy-h-14", category: c, difficulty: "historian", type: "mcq",
    prompt: "Pandit Bhimsen Joshi, one of the great khayal singers, belonged to which gharana?",
    options: ["Gwalior", "Kirana", "Jaipur-Atrauli", "Patiala"],
    answer: 1,
    explanation: {
      title: "Bhimsen Joshi and the Kirana gharana",
      body: "Bhimsen Joshi trained under Sawai Gandharva, a disciple of Ustad Abdul Karim Khan, founder of the Kirana gharana. The Kirana style is known for slow, careful unfolding of each note. Joshi received the Bharat Ratna in 2009.",
      trivia: "Joshi started the Sawai Gandharva Music Festival in Pune in memory of his guru. It is now one of India's best-known classical music festivals.",
    },
    source: SRC.britannica("biography/Bhimsen-Joshi", "Bhimsen Joshi"),
  },
  {
    id: "rhy-h-15", category: c, difficulty: "historian", type: "mcq",
    prompt: "Tyagaraja composed most of his kritis in which language?",
    options: ["Tamil", "Sanskrit", "Telugu", "Kannada"],
    answer: 2,
    explanation: {
      title: "Tyagaraja's Telugu kritis",
      body: "Although he lived in Tamil Nadu, Tyagaraja wrote most of his compositions in Telugu, the prestige language of music at the Thanjavur court at that time. Hundreds of his kritis are still sung, and the Tyagaraja Aradhana festival at Thiruvaiyaru draws musicians every year.",
    },
    source: SRC.britannica("biography/Tyagaraja", "Tyagaraja"),
  },
  {
    id: "rhy-h-16", category: c, difficulty: "historian", type: "mcq",
    prompt: "The light-classical form thumri flourished in the 19th century at the court of which ruler?",
    options: ["Wajid Ali Shah of Awadh", "Maharaja Ranjit Singh", "Tipu Sultan", "Nizam Mir Osman Ali Khan"],
    answer: 0,
    explanation: {
      title: "Thumri in Lucknow",
      body: "Thumri, a romantic and expressive vocal form, grew under the patronage of Nawab Wajid Ali Shah of Awadh in Lucknow. The nawab was himself a poet, composer and patron of Kathak dance. Banaras later became another major centre of thumri.",
    },
    source: SRC.britannica("art/thumri", "Thumri"),
  },
  {
    id: "rhy-h-17", category: c, difficulty: "historian", type: "true_false",
    prompt: "True or false: Sattriya was recognised as a classical dance by the Sangeet Natak Akademi in the year 2000.",
    answer: true,
    explanation: {
      title: "Sattriya joins the classical list",
      body: "Sattriya was created in the 15th and 16th centuries by the saint Srimanta Sankardev as part of the Vaishnava movement in Assam. It was preserved in the sattras (monasteries) for centuries and was recognised as a classical dance in 2000.",
    },
    source: SRC.sna,
  },
  {
    id: "rhy-h-18", category: c, difficulty: "historian", type: "odd_one_out",
    prompt: "Which of these is NOT a genre of Hindustani vocal music?",
    options: ["Dhrupad", "Khayal", "Tappa", "Kriti"],
    answer: 3,
    explanation: {
      title: "Kriti is Carnatic",
      body: "The kriti is the central song form of Carnatic music, with a set structure of pallavi, anupallavi and charanam. Dhrupad, khayal and tappa are all Hindustani genres. Tappa began among camel riders of Punjab and is known for its quick, rippling phrases.",
    },
    source: SRC.britannica("art/Karnatak-music", "Carnatic music"),
  },
  {
    id: "rhy-h-19", category: c, difficulty: "historian", type: "mcq",
    prompt: "What does the name Mohiniyattam mean?",
    options: ["Dance of the enchantress", "Dance of the warrior", "Dance of the harvest", "Dance of the temple lamp"],
    answer: 0,
    explanation: {
      title: "Mohiniyattam, the enchantress's dance",
      body: "Mohiniyattam takes its name from Mohini, the enchanting female form taken by Vishnu in Hindu mythology. It is a solo dance of Kerala known for gentle swaying movements and is traditionally performed by women in white and gold kasavu costumes.",
      trivia: "The poet Vallathol Narayana Menon founded the Kerala Kalamandalam in 1930, which revived both Mohiniyattam and Kathakali.",
    },
    source: SRC.britannica("art/mohiniyattam", "Mohiniyattam"),
  },
  {
    id: "rhy-h-20", category: c, difficulty: "historian", type: "chronology",
    prompt: "Arrange these music figures by when they lived, earliest first.",
    items: ["Sharngadeva", "Purandara Dasa", "Tyagaraja", "Vishnu Narayan Bhatkhande"],
    explanation: {
      title: "Seven centuries of music",
      body: "Sharngadeva wrote the Sangita Ratnakara in the 13th century. Purandara Dasa (about 1484 to 1564) laid the teaching foundations of Carnatic music. Tyagaraja (1767 to 1847) is the best known of the Carnatic Trinity, and Vishnu Narayan Bhatkhande (1860 to 1936) organised Hindustani ragas into the thaat system.",
    },
    source: SRC.britannica("art/South-Asian-arts", "South Asian arts"),
  },
  {
    id: "rhy-h-21", category: c, difficulty: "historian", type: "mcq",
    prompt: "Kutiyattam, one of the oldest living theatre traditions in the world, is performed in which language?",
    options: ["Sanskrit, with Malayalam passages", "Tamil only", "Pali", "Kannada"],
    answer: 0,
    explanation: {
      title: "Kutiyattam's ancient language",
      body: "Kutiyattam of Kerala performs classical Sanskrit plays, with clowns called vidushakas explaining the action in Malayalam. It was traditionally staged in temple theatres called koothambalams. UNESCO recognised it in 2008 (first proclaimed a masterpiece in 2001).",
      trivia: "A single act of Kutiyattam can take several nights to perform in full.",
    },
    source: SRC.unescoIchIndia,
  },
];
