/**
 * Punjabi (Gurmukhi) and Urdu names for heritage registry entries, keyed by id.
 * English and Hindi names live in registry.ts.
 */
export const HERITAGE_NAMES: Record<string, { pa: string; ur: string }> = {
  // Performing arts, rituals, festivals and crafts
  kutiyattam: { pa: "ਕੂਡੀਆੱਟਮ", ur: "کوڈیاٹم" },
  mudiyettu: { pa: "ਮੁਡੀਏੱਟੂ", ur: "مڈیٹو" },
  ramman: { pa: "ਰੰਮਾਣ", ur: "رمّان" },
  chhau: { pa: "ਛਊ ਨਾਚ", ur: "چھاؤ رقص" },
  kalbelia: { pa: "ਕਾਲਬੇਲੀਆ", ur: "کال بیلیا" },
  sankirtana: { pa: "ਸੰਕੀਰਤਨ", ur: "سنکیرتن" },
  "ladakh-chanting": { pa: "ਲੱਦਾਖ਼ ਦਾ ਬੋਧੀ ਮੰਤਰ ਜਾਪ", ur: "لداخ کا بودھ منتر جاپ" },
  thatheras: { pa: "ਠਠੇਰਾ ਧਾਤ ਕਲਾ", ur: "ٹھٹھیرا دھاتی فن" },
  "vedic-chanting": { pa: "ਵੈਦਿਕ ਮੰਤਰ ਜਾਪ", ur: "ویدک منتر جاپ" },
  ramlila: { pa: "ਰਾਮਲੀਲਾ", ur: "رام لیلا" },
  garba: { pa: "ਗਰਬਾ", ur: "گربا" },
  "durga-puja": { pa: "ਦੁਰਗਾ ਪੂਜਾ", ur: "درگا پوجا" },
  "kumbh-mela": { pa: "ਕੁੰਭ ਮੇਲਾ", ur: "کمبھ میلہ" },
  yoga: { pa: "ਯੋਗ", ur: "یوگ" },
  deepavali: { pa: "ਦੀਪਾਵਲੀ", ur: "دیپاولی" },
  theyyam: { pa: "ਤੇਯਮ", ur: "تییم" },
  yakshagana: { pa: "ਯਕਸ਼ਗਾਨ", ur: "یکش گان" },
  kathakali: { pa: "ਕਥਕਲੀ", ur: "کتھکلی" },
  bharatanatyam: { pa: "ਭਰਤਨਾਟਿਅਮ", ur: "بھرت ناٹیم" },
  kathak: { pa: "ਕੱਥਕ", ur: "کتھک" },
  odissi: { pa: "ਓਡੀਸੀ", ur: "اوڈیسی" },
  manipuri: { pa: "ਮਣੀਪੁਰੀ ਨਾਚ", ur: "منی پوری رقص" },
  sattriya: { pa: "ਸੱਤਰੀਆ", ur: "ستریا" },
  kuchipudi: { pa: "ਕੁਚੀਪੁੜੀ", ur: "کچی پوڑی" },
  mohiniyattam: { pa: "ਮੋਹਿਨੀਅੱਟਮ", ur: "موہنی اٹم" },
  lavani: { pa: "ਲਾਵਣੀ", ur: "لاونی" },
  bihu: { pa: "ਬਿਹੂ", ur: "بیہو" },
  dhrupad: { pa: "ਧ੍ਰੁਪਦ", ur: "دھروپد" },
  "hornbill-festival": { pa: "ਹੌਰਨਬਿਲ ਉਤਸਵ", ur: "ہارن بل میلہ" },
  onam: { pa: "ਓਣਮ", ur: "اونم" },
  pongal: { pa: "ਪੋਂਗਲ", ur: "پونگل" },
  "rath-yatra": { pa: "ਰਥ ਯਾਤਰਾ", ur: "رتھ یاترا" },
  "thrissur-pooram": { pa: "ਤ੍ਰਿਸ਼ੂਰ ਪੂਰਮ", ur: "ترشور پورم" },
  "mysuru-dasara": { pa: "ਮੈਸੂਰ ਦੁਸਹਿਰਾ", ur: "میسور دسہرا" },
  khejarli: { pa: "ਬਿਸ਼ਨੋਈ ਰੁੱਖ ਸੰਭਾਲ", ur: "بشنوئی درخت تحفظ" },
  chipko: { pa: "ਚਿਪਕੋ ਅੰਦੋਲਨ", ur: "چپکو تحریک" },
  warli: { pa: "ਵਾਰਲੀ ਚਿੱਤਰਕਾਰੀ", ur: "وارلی مصوری" },
  madhubani: { pa: "ਮਧੁਬਨੀ ਚਿੱਤਰਕਾਰੀ", ur: "مدھوبنی مصوری" },
  pattachitra: { pa: "ਪੱਟਚਿੱਤਰ", ur: "پٹ چتر" },
  kalamkari: { pa: "ਕਲਮਕਾਰੀ", ur: "قلمکاری" },
  phad: { pa: "ਫੜ ਚਿੱਤਰਕਾਰੀ", ur: "پھڑ مصوری" },
  dhokra: { pa: "ਢੋਕਰਾ ਧਾਤ ਢਲਾਈ", ur: "ڈھوکرا دھات ڈھلائی" },
  bidriware: { pa: "ਬਿਦਰੀ ਕਲਾ", ur: "بیدری کاری" },
  channapatna: { pa: "ਚੰਨਪਟਨਾ ਖਿਡੌਣੇ", ur: "چنّاپٹنا کھلونے" },
  chikankari: { pa: "ਚਿਕਨਕਾਰੀ", ur: "چکن کاری" },
  phulkari: { pa: "ਫੁਲਕਾਰੀ", ur: "پھلکاری" },
  "blue-pottery": { pa: "ਨੀਲੀ ਮਿੱਟੀ ਕਲਾ", ur: "نیلی کوزہ گری" },
  pashmina: { pa: "ਪਸ਼ਮੀਨਾ ਬੁਣਾਈ", ur: "پشمینہ بنائی" },
  "kanchipuram-silk": { pa: "ਕਾਂਚੀਪੁਰਮ ਰੇਸ਼ਮ ਬੁਣਾਈ", ur: "کانچی پورم ریشم بنائی" },
  "pochampally-ikat": { pa: "ਪੋਚਮਪੱਲੀ ਇਕਤ", ur: "پوچم پلی اِکت" },
  "tanjore-painting": { pa: "ਤੰਜੌਰ ਚਿੱਤਰਕਾਰੀ", ur: "تنجور مصوری" },
  kumartuli: { pa: "ਕੁਮਾਰਟੁਲੀ ਦੀਆਂ ਮੂਰਤੀਆਂ", ur: "کمارٹولی کی مورتیاں" },

  // Sites
  "taj-mahal": { pa: "ਤਾਜ ਮਹਿਲ", ur: "تاج محل" },
  konark: { pa: "ਸੂਰਜ ਮੰਦਰ, ਕੋਣਾਰਕ", ur: "سورج مندر، کونارک" },
  hampi: { pa: "ਹੰਪੀ", ur: "ہمپی" },
  khajuraho: { pa: "ਖਜੁਰਾਹੋ ਦੇ ਮੰਦਰ", ur: "کھجوراہو کے مندر" },
  "rani-ki-vav": { pa: "ਰਾਣੀ ਕੀ ਵਾਵ", ur: "رانی کی واو" },
  dholavira: { pa: "ਧੋਲਾਵੀਰਾ", ur: "دھولاویرا" },
  lothal: { pa: "ਲੋਥਲ", ur: "لوتھل" },
  sanchi: { pa: "ਸਾਂਚੀ", ur: "سانچی" },
  ajanta: { pa: "ਅਜੰਤਾ ਦੀਆਂ ਗੁਫ਼ਾਵਾਂ", ur: "اجنتا کے غار" },
  ellora: { pa: "ਏਲੋਰਾ ਦੀਆਂ ਗੁਫ਼ਾਵਾਂ", ur: "ایلورا کے غار" },
  elephanta: { pa: "ਐਲੀਫੈਂਟਾ ਦੀਆਂ ਗੁਫ਼ਾਵਾਂ", ur: "ایلیفنٹا کے غار" },
  mahabodhi: { pa: "ਮਹਾਬੋਧੀ ਮੰਦਰ", ur: "مہابودھی مندر" },
  sarnath: { pa: "ਸਾਰਨਾਥ", ur: "سارناتھ" },
  nalanda: { pa: "ਨਾਲੰਦਾ ਮਹਾਵਿਹਾਰ", ur: "نالندہ مہاوہار" },
  "chola-temples": { pa: "ਬ੍ਰਿਹਦੀਸ਼ਵਰ ਮੰਦਰ, ਤੰਜਾਵੁਰ", ur: "برہدیشور مندر، تنجاور" },
  mahabalipuram: { pa: "ਮਹਾਬਲੀਪੁਰਮ", ur: "مہابلی پورم" },
  pattadakal: { pa: "ਪੱਟਦਕਲ", ur: "پٹدکل" },
  hoysala: { pa: "ਹੋਯਸਲ ਮੰਦਰ", ur: "ہویسل مندر" },
  ramappa: { pa: "ਰਾਮੱਪਾ ਮੰਦਰ", ur: "رامپا مندر" },
  "gol-gumbaz": { pa: "ਗੋਲ ਗੁੰਬਜ਼", ur: "گول گنبد" },
  "qutb-minar": { pa: "ਕੁਤੁਬ ਮੀਨਾਰ", ur: "قطب مینار" },
  "red-fort": { pa: "ਲਾਲ ਕਿਲ੍ਹਾ", ur: "لال قلعہ" },
  "humayun-tomb": { pa: "ਹੁਮਾਯੂੰ ਦਾ ਮਕਬਰਾ", ur: "ہمایوں کا مقبرہ" },
  "fatehpur-sikri": { pa: "ਫ਼ਤਿਹਪੁਰ ਸੀਕਰੀ", ur: "فتح پور سیکری" },
  "jantar-mantar": { pa: "ਜੰਤਰ ਮੰਤਰ, ਜੈਪੁਰ", ur: "جنتر منتر، جے پور" },
  "jaipur-city": { pa: "ਜੈਪੁਰ ਦਾ ਪਰਕੋਟਾ ਸ਼ਹਿਰ", ur: "جے پور کا فصیل بند شہر" },
  ahmedabad: { pa: "ਇਤਿਹਾਸਕ ਅਹਿਮਦਾਬਾਦ", ur: "تاریخی احمد آباد" },
  bhimbetka: { pa: "ਭੀਮਬੇਟਕਾ ਚਟਾਨੀ ਆਸਰੇ", ur: "بھیم بیٹکا چٹانی پناہ گاہیں" },
  csmt: { pa: "ਛਤਰਪਤੀ ਸ਼ਿਵਾਜੀ ਮਹਾਰਾਜ ਟਰਮੀਨਸ", ur: "چھترپتی شیواجی مہاراج ٹرمینس" },
  "mumbai-deco": { pa: "ਮੁੰਬਈ ਦਾ ਵਿਕਟੋਰੀਅਨ ਅਤੇ ਆਰਟ ਡੈਕੋ", ur: "ممبئی کا وکٹورین اور آرٹ ڈیکو" },
  "chandigarh-capitol": { pa: "ਕੈਪੀਟਲ ਕੰਪਲੈਕਸ, ਚੰਡੀਗੜ੍ਹ", ur: "کیپیٹل کمپلیکس، چنڈی گڑھ" },
  santiniketan: { pa: "ਸ਼ਾਂਤੀਨਿਕੇਤਨ", ur: "شانتی نکیتن" },
  moidams: { pa: "ਚਰਾਈਦੇਵ ਦੇ ਮੋਈਦਾਮ", ur: "چرائیدیو کے موئیدام" },
  "mountain-railways": { pa: "ਦਾਰਜੀਲਿੰਗ ਹਿਮਾਲਿਅਨ ਰੇਲਵੇ", ur: "دارجلنگ ہمالین ریلوے" },
  raigad: { pa: "ਰਾਏਗੜ੍ਹ ਕਿਲ੍ਹਾ", ur: "رائے گڑھ قلعہ" },
  jhansi: { pa: "ਝਾਂਸੀ ਦਾ ਕਿਲ੍ਹਾ", ur: "جھانسی کا قلعہ" },
  srirangapatna: { pa: "ਸ਼੍ਰੀਰੰਗਪਟਣ", ur: "سری رنگ پٹن" },
  warangal: { pa: "ਵਾਰੰਗਲ ਕਿਲ੍ਹਾ", ur: "ورنگل قلعہ" },
  pataliputra: { pa: "ਪਾਟਲੀਪੁੱਤਰ (ਪਟਨਾ)", ur: "پاٹلی پتر (پٹنہ)" },

  // Foods
  "darjeeling-tea": { pa: "ਦਾਰਜੀਲਿੰਗ ਚਾਹ", ur: "دارجلنگ چائے" },
  "assam-tea": { pa: "ਅਸਾਮ ਚਾਹ", ur: "آسام چائے" },
  "kashmir-saffron": { pa: "ਕਸ਼ਮੀਰੀ ਕੇਸਰ", ur: "کشمیری زعفران" },
  "tirupati-laddu": { pa: "ਤਿਰੂਪਤੀ ਲੱਡੂ", ur: "تروپتی لڈو" },
  alphonso: { pa: "ਹਾਪੁਸ ਅੰਬ", ur: "ہاپس آم" },
  "bikaneri-bhujia": { pa: "ਬੀਕਾਨੇਰੀ ਭੁਜੀਆ", ur: "بیکانیری بھجیا" },
  "hyderabadi-haleem": { pa: "ਹੈਦਰਾਬਾਦੀ ਹਲੀਮ", ur: "حیدرآبادی حلیم" },
  "litti-chokha": { pa: "ਲਿੱਟੀ ਚੋਖਾ", ur: "لٹی چوکھا" },
  dhokla: { pa: "ਢੋਕਲਾ", ur: "ڈھوکلا" },
  feni: { pa: "ਗੋਆ ਫੇਨੀ", ur: "گوا فینی" },
  "malabar-pepper": { pa: "ਮਾਲਾਬਾਰ ਕਾਲੀ ਮਿਰਚ", ur: "مالابار کالی مرچ" },
  "joynagar-moa": { pa: "ਜੈਨਗਰ ਮੋਆ", ur: "جے نگر موآ" },
  "dharwad-pedha": { pa: "ਧਾਰਵਾੜ ਪੇੜਾ", ur: "دھارواڑ پیڑا" },
  "coorg-coffee": { pa: "ਕੂਰਗ ਕੌਫ਼ੀ", ur: "کورگ کافی" },
  rasgulla: { pa: "ਰਸਗੁੱਲਾ", ur: "رس گلا" },
  "mysore-pak": { pa: "ਮੈਸੂਰ ਪਾਕ", ur: "میسور پاک" },
  basmati: { pa: "ਬਾਸਮਤੀ ਚੌਲ", ur: "باسمتی چاول" },
  millets: { pa: "ਮੋਟੇ ਅਨਾਜ", ur: "موٹے اناج" },
  chettinad: { pa: "ਚੇੱਟੀਨਾਡ ਪਕਵਾਨ", ur: "چیٹی ناڈ کھانے" },
};
